### ISSUE TITLE
MongoDB Extended JSON serialization/derialization

### ISSUE THREAD

**Issue by tuffnatty** [JohnAD/bson#5]
Hi. The standard [de]serialization format for BSON is [MongoDB Extended JSON](https://docs.mongodb.com/manual/reference/mongodb-extended-json/). Every "official" BSON language binding includes (de)serialization to/from this format. I suppose the plan behind proc `$`*(bs: Bson): string was also to support that?

I need this functionality in any case. Would you like it to be part of this package, or should I start a dedicated one?

**Comment by JohnAD** [comment]
The `$` proc is was intended to be a "visual convenience" rather than any kind of conversion to JSON. It is fairly ad-hoc.

However, having formal JSON serialization/deserialization added to this package would be extremely useful. It could either be put directly into the main source or included as a sub-module; which might be cleaner. Perhaps in `src/bson/jsonserialize.nim` so that it can be used with an extra `import bson/jsonserialize`.

Yes, I'd love to see Extended JSON serialization/deserialization added to the package.

**Comment by JohnAD** [comment]
BTW, I'm using a poorly-documented but convenient utility I wrote called `docnimble` to generate the documentation. It has has a lot of features that go way beyond `nim doc`.  If, when writing the code, you put the documentation for the public procedures in the following form:

```nim
## generic documentation for the whole nim module
## blah blah

proc xyz*() =
  ## documentation for the procedures
  ## blah blah
  discard
```

I'll generate the docs files for you.

... this reminds me, I should probably make `docnimble` publicly visible soon.

**Comment by JohnAD** [comment]
Just curious, in regards to supporting the [`json`](https://nim-lang.org/docs/json.html) module in Nim's standard library, were you thinking of this to generate a string:

Bson ->(new procedure)-> Json ->(`json`'s `pretty`)-> string

or generating a string first, allowing the user to parse into `Json`:

Bson ->(new procedure)-> string ->(`json`'s `parseJson`)-> Json

**Comment by tuffnatty** [comment]
Generating a string directly seems more robust to me, performance-wise as well - generating a string will always be faster than dealing with the whole `json` module's structure. However, `parsejson` is good, so I am going to use it.

**Comment by JohnAD** [comment]
@tuffnatty 

I had noticed quite few inconsistencies with the library's use of `$`. To clarify a bit, I asked the community this:

https://forum.nim-lang.org/t/5682

Given Araq's response, I think it makes sense to:

* use your up-and-coming json extended serialization for `$` against a document.
  * if used on another bson kind, use the "inside equivalent" of that same serialization.
* Limit the use of `toString()` to string types (and near-string types such as as `BsonKindJSCode` and oids)

Thoughts?

BTW, I'm happy to collaborate on your branch if you would like a helper.

**Comment by tuffnatty** [comment]
@JohnAD I have working code to convert raw binary BSON string to ExtJson string (it's a bit faster if one does not need the intermediate Bson structure, but I guess most people would need it), and code to convert ExtJson string to Bson object. It is not quite ready for inclusion in this library. (And it would take deeper integration than adding a submodule, as the proper integration would need access to protected Bson fields or additional Bson methods to provide this access; now it serializes fields missing proper getters to bytes, then parses that). As I am unsure if I will have any time for porting soon, here is the code, please use it as you like: https://github.com/tuffnatty/bsonext.nim

**Comment by JohnAD** [comment]
Your code was very useful. I'll have something ready later today.

**Comment by JohnAD** [comment]
Done!

I've changed `$` to be a ExtJson canonical serialization with indentation; additionally, `toJson` does a minimized ExtJson serialization by default. And `pretty` does a human readable version in the "relaxed" styling that still meets the non-canonical specs.

I've also created a function for restoring a string. One reads the string into the Json library first. Then, one can run `interpretExtendedJson` that takes the fields with dollar signs in them and reinterprets that back into BSON. Since BSON never accepts fields with dollar signs, they are interpreted into nulls if all else fails.

https://github.com/JohnAD/bson/blob/master/docs/bson-ref.rst#interpretextendedjson

**Comment by tuffnatty** [comment]
> Since BSON never accepts fields with dollar signs

The BSON spec does not mention this restriction.
MongoDB 3.6+ explicitly permits dots and dollar signs in field names (except starting a top-level field name with a dollar sign):
https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names

**Comment by JohnAD** [comment]
Good catch. Did not know of the change (in the mongodb context). I will change the code to only examine the first character for a $ for the interpretation function.

I don't think the rest of the library cares currently, but I'll confirm that and add unit tests.
